// Code generated by protoc-gen-go. DO NOT EDIT.
// source: account/acct_def.proto

package account

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GetAccountReq struct {
	ID                   int64    `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetAccountReq) Reset()         { *m = GetAccountReq{} }
func (m *GetAccountReq) String() string { return proto.CompactTextString(m) }
func (*GetAccountReq) ProtoMessage()    {}
func (*GetAccountReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_126bb8ee871da744, []int{0}
}

func (m *GetAccountReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAccountReq.Unmarshal(m, b)
}
func (m *GetAccountReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAccountReq.Marshal(b, m, deterministic)
}
func (m *GetAccountReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAccountReq.Merge(m, src)
}
func (m *GetAccountReq) XXX_Size() int {
	return xxx_messageInfo_GetAccountReq.Size(m)
}
func (m *GetAccountReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAccountReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetAccountReq proto.InternalMessageInfo

func (m *GetAccountReq) GetID() int64 {
	if m != nil {
		return m.ID
	}
	return 0
}

type GetAccountRsp struct {
	Acct                 *Account `protobuf:"bytes,1,opt,name=acct,proto3" json:"acct,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetAccountRsp) Reset()         { *m = GetAccountRsp{} }
func (m *GetAccountRsp) String() string { return proto.CompactTextString(m) }
func (*GetAccountRsp) ProtoMessage()    {}
func (*GetAccountRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_126bb8ee871da744, []int{1}
}

func (m *GetAccountRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAccountRsp.Unmarshal(m, b)
}
func (m *GetAccountRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAccountRsp.Marshal(b, m, deterministic)
}
func (m *GetAccountRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAccountRsp.Merge(m, src)
}
func (m *GetAccountRsp) XXX_Size() int {
	return xxx_messageInfo_GetAccountRsp.Size(m)
}
func (m *GetAccountRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAccountRsp.DiscardUnknown(m)
}

var xxx_messageInfo_GetAccountRsp proto.InternalMessageInfo

func (m *GetAccountRsp) GetAcct() *Account {
	if m != nil {
		return m.Acct
	}
	return nil
}

type Account struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Email                string   `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Password             string   `protobuf:"bytes,4,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Account) Reset()         { *m = Account{} }
func (m *Account) String() string { return proto.CompactTextString(m) }
func (*Account) ProtoMessage()    {}
func (*Account) Descriptor() ([]byte, []int) {
	return fileDescriptor_126bb8ee871da744, []int{2}
}

func (m *Account) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Account.Unmarshal(m, b)
}
func (m *Account) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Account.Marshal(b, m, deterministic)
}
func (m *Account) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Account.Merge(m, src)
}
func (m *Account) XXX_Size() int {
	return xxx_messageInfo_Account.Size(m)
}
func (m *Account) XXX_DiscardUnknown() {
	xxx_messageInfo_Account.DiscardUnknown(m)
}

var xxx_messageInfo_Account proto.InternalMessageInfo

func (m *Account) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Account) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Account) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *Account) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func init() {
	proto.RegisterType((*GetAccountReq)(nil), "account.GetAccountReq")
	proto.RegisterType((*GetAccountRsp)(nil), "account.GetAccountRsp")
	proto.RegisterType((*Account)(nil), "account.Account")
}

func init() { proto.RegisterFile("account/acct_def.proto", fileDescriptor_126bb8ee871da744) }

var fileDescriptor_126bb8ee871da744 = []byte{
	// 180 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x4b, 0x4c, 0x4e, 0xce,
	0x2f, 0xcd, 0x2b, 0xd1, 0x4f, 0x4c, 0x4e, 0x2e, 0x89, 0x4f, 0x49, 0x4d, 0xd3, 0x2b, 0x28, 0xca,
	0x2f, 0xc9, 0x17, 0x62, 0x87, 0x8a, 0x2b, 0xc9, 0x73, 0xf1, 0xba, 0xa7, 0x96, 0x38, 0x42, 0x78,
	0x41, 0xa9, 0x85, 0x42, 0x7c, 0x5c, 0x4c, 0x9e, 0x2e, 0x12, 0x8c, 0x0a, 0x8c, 0x1a, 0xcc, 0x41,
	0x4c, 0x9e, 0x2e, 0x4a, 0xa6, 0x28, 0x0a, 0x8a, 0x0b, 0x84, 0x54, 0xb8, 0x58, 0x40, 0x86, 0x81,
	0x95, 0x70, 0x1b, 0x09, 0xe8, 0x41, 0x4d, 0xd2, 0x83, 0x29, 0x01, 0xcb, 0x2a, 0xc5, 0x73, 0xb1,
	0x43, 0x05, 0x40, 0x26, 0x66, 0xa6, 0xc0, 0x4c, 0xcc, 0x4c, 0x11, 0x12, 0xe2, 0x62, 0xc9, 0x4b,
	0xcc, 0x4d, 0x95, 0x60, 0x52, 0x60, 0xd4, 0xe0, 0x0c, 0x02, 0xb3, 0x85, 0x44, 0xb8, 0x58, 0x53,
	0x73, 0x13, 0x33, 0x73, 0x24, 0x98, 0xc1, 0x82, 0x10, 0x8e, 0x90, 0x14, 0x17, 0x47, 0x41, 0x62,
	0x71, 0x71, 0x79, 0x7e, 0x51, 0x8a, 0x04, 0x0b, 0x58, 0x02, 0xce, 0x77, 0xe2, 0x8c, 0x82, 0xf9,
	0x21, 0x89, 0x0d, 0xec, 0x27, 0x63, 0x40, 0x00, 0x00, 0x00, 0xff, 0xff, 0x24, 0x00, 0x46, 0x26,
	0xed, 0x00, 0x00, 0x00,
}
